# Generated by Django 5.1 on 2024-08-22 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="trans_date",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="trans_method",
            field=models.CharField(
                choices=[
                    ("ATM", "ATM 거래"),
                    ("TRANSFER", "계좌이체"),
                    ("AUTOMATIC_TRANSFER", "자동이체"),
                    ("CARD", "카드결제"),
                    ("INTEREST", "이자"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="trans_type",
            field=models.CharField(choices=[("DEPOSIT", "입금"), ("WITHDRAW", "출금")], max_length=20),
        ),
    ]
