# Generated by Django 5.1.1 on 2024-09-05 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Analysis",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "about",
                    models.CharField(
                        choices=[("TOTAL_SPENDING", "총 지출"), ("TOTAL_INCOME", "총 수입")], max_length=20
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("DAILY", "일간"), ("WEEKLY", "주간"), ("MONTHLY", "월간"), ("YEARLY", "연간")],
                        max_length=7,
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("description", models.TextField()),
                ("result_image", models.ImageField(blank=True, max_length=255, null=True, upload_to="analysis/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
